# Generated by Django 4.2.3 on 2023-07-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplealbum',
            name='album_media',
        ),
        migrations.AddField(
            model_name='media',
            name='media_album',
            field=models.ManyToManyField(related_name='media_albums_multiple', to='storage.multiplealbum'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_path',
            field=models.FileField(blank=True, upload_to='media_storage/2023/07/26/<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x7fad9a1274d0>'),
        ),
    ]
