# Generated by Django 4.2.3 on 2023-07-26 20:42

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_multiplealbum_album_media_media_media_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_path',
            field=models.FileField(upload_to=storage.models.upload_to),
        ),
    ]
