# Generated by Django 4.2.3 on 2023-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_media_media_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_album',
            field=models.ManyToManyField(blank=True, null=True, related_name='media_albums_multiple', to='storage.multiplealbum'),
        ),
    ]
